const VALIDATION_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const CAST_ERROR = 500;

const REQUEST_OK = 200;
const CREATE_OK = 201;

module.exports = {
  VALIDATION_ERROR, NOT_FOUND_ERROR, CAST_ERROR, REQUEST_OK, CREATE_OK,
};
